FROM triumfmlutils/baseml:v0.8

# Install Graphviz.
RUN pip install graphviz

# Install PyTorch Geometric.
RUN pip install --verbose --no-cache-dir torch-scatter \
 && pip install --verbose --no-cache-dir torch-sparse \
 && pip install --verbose --no-cache-dir torch-cluster \
 && pip install --verbose --no-cache-dir torch-spline-conv \
 && pip install torch-geometric
